# Generated by Django 4.1.13 on 2023-11-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="train",
            name="id",
        ),
        migrations.AddField(
            model_name="train",
            name="Delayed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="train",
            name="Train_no",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
