# Generated by Django 4.1.13 on 2023-11-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_remove_train_id_train_delayed_alter_train_train_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="Logic1",
            fields=[
                ("sno", models.AutoField(primary_key=True, serialize=False)),
                ("quest", models.TextField()),
                ("ans", models.TextField()),
            ],
        ),
    ]
